services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - mongo
    networks:
      - stock-net

  mongo:
    image: mongo:7
    container_name: stock-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - stock-net

volumes:
  mongo-data:

networks:
  stock-net:
    driver: bridge
